# Generated by Django 6.0.3 on 2026-03-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
